### PR TITLE
Auto-update README with new AMI IDs after release.

### PR DESCRIPTION
**Pull request by malcyon**
I don't like copy-pasting AMI-IDs after a release. This will make the Jenkins job do it for me.

### CODE REVIEW

**Comment by malcyon** [comment]
@bernd My tenative plan for testing this:

- Change `packer/aws.json` to only publish to one region.
- Change AMI Name so it doesn't conflict with other image names.
- Run Graylog2-Images release job against `automate-readme-update` branch using Graylog version 3.3.2-1
- Deregister AMI image after it's done. 
- README.md changes should be done on the `automate-readme-update` branch, so it shouldn't affect the main branch.

**Comment by malcyon** [comment]
It is almost working. I just need to:

- Remove the revision from the version number, so that `3.3.2-1` becomes `3.3.2`.
- Remove the extra `)` at the end of the AMI id. Why does the ruby script add that? I guess I'll just remove it..

**Comment by malcyon** [comment]
It works. Going to leave the revision in there. It doesn't hurt anything.

**Review by bernd — APPROVED** [review]
Awesome, thank you! :+1:

**Pull request merged**
